import 'dotenv/config'

const env = {
  MODE: process.env.MODE,
  DATABASE_NAME: process.env.DATABASE_NAME,
  BOARD_COLLECTION_NAME: process.env.BOARD_COLLECTION_NAME,
  CARD_COLLECTION_NAME: process.env.CARD_COLLECTION_NAME,
  COLUMN_COLLECTION_NAME: process.env.COLUMN_COLLECTION_NAME,
  USER_COLLECTION_NAME: process.env.USER_COLLECTION_NAME,
  MONGODB_URI: process.env.MONGODB_URI,
  APP_HOST: process.env.APP_HOST,
  APP_PORT: process.env.APP_PORT,
  REFRESH_TOKEN_SECRET_KEY: process.env.REFRESH_TOKEN_SECRET_KEY,
  ACCESS_TOKEN_SECRET_KEY: process.env.ACCESS_TOKEN_SECRET_KEY,
  EMAIL_SENDER: process.env.EMAIL_SENDER,
  EMAIL_PASSWORD: process.env.EMAIL_PASSWORD,
  WEBSITE_DOMAIN_DEV: process.env.WEBSITE_DOMAIN_DEV,
  ACCESS_TOKEN_TIME_LIFE: process.env.ACCESS_TOKEN_TIME_LIFE,
  REFRESH_TOKEN_TIME_LIFE: process.env.REFRESH_TOKEN_TIME_LIFE,
  API_SEND_MAIL: process.env.API_SEND_MAIL,
  CLOUDINARY_NAME: process.env.CLOUDINARY_NAME,
  CLOUDINARY_API_KEY: process.env.CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET: process.env.CLOUDINARY_API_SECRET,
  INVITATION_COLLECTION_NAME: process.env.INVITATION_COLLECTION_NAME
}

export default env

